'use client';
import {useEffect,useState} from 'react';
import {ClipboardList,ChevronDown,Plus} from 'lucide-react';
import {api} from '@/lib/api';
export default function Page(){
 const [rows,setRows]=useState<any[]>([]); const [schemes,setSchemes]=useState<any[]>([]); const [schemeId,setSchemeId]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);try{setRows(await fetch('/api/applications',{cache:'no-store'}).then(r=>r.json()));setSchemes(await api.schemes())}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const create=async()=>{if(!schemeId)return;setBusy(true);try{await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scheme_id:Number(schemeId)})});setSchemeId('');await load()}finally{setBusy(false)}};
 const advance=async(r:any)=>{const next:Record<string,string>={"Not Started":"Preparing","Preparing":"Submitted","Submitted":"Under Verification","Under Verification":"Completed","Completed":"Completed"}[String(r.status)]||'Preparing';await fetch(`/api/applications/${r.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:next})});await load()};
 return <div className="min-h-screen bg-slate-50"><div className="mx-auto max-w-6xl px-5 py-8"><div className="rounded-3xl bg-gradient-to-br from-[#0b1f3a] to-[#155eef] p-7 text-white"><div className="flex items-center gap-3"><ClipboardList/><div><p className="text-xs font-bold uppercase tracking-wider text-blue-200">SAHAKAR SAHAYAK</p><h1 className="text-3xl font-black">Application Guidance Tracker</h1></div></div><p className="mt-3 max-w-2xl text-sm text-blue-100">A local prototype for organizing application guidance. Government submission and status are not connected.</p></div>
 <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>DEMO APPLICATION TRACKING</b> — statuses shown here are simulated guidance states, not official application statuses.</div>
 <section className="card mt-5 rounded-2xl p-5"><h2 className="font-bold">Start an application guidance record</h2><div className="mt-3 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><select value={schemeId} onChange={e=>setSchemeId(e.target.value)} className="w-full appearance-none rounded-xl border bg-white px-4 py-3 text-sm"><option value="">Select a scheme</option>{schemes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3.5 text-slate-400" size={18}/></div><button disabled={!schemeId||busy} onClick={create} className="flex items-center justify-center gap-2 rounded-xl bg-[#0b1f3a] px-5 py-3 text-sm font-bold text-white disabled:opacity-50"><Plus size={17}/> Add guidance</button></div></section>
 <div className="mt-5 space-y-4">{loading?<div className="card rounded-2xl p-6">Loading application guidance…</div>:rows.map(r=><div key={r.id} className="card rounded-2xl p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">{r.mode}</p><h2 className="mt-1 text-lg font-bold text-[#0b1f3a]">{r.scheme_name}</h2><p className="mt-1 text-sm text-slate-500">Current step: {r.current_step}</p></div><span className="h-fit rounded-full bg-blue-50 px-3 py-1.5 text-xs font-bold text-blue-700">{r.status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Documents</p><p className="mt-1 text-sm font-semibold">{r.documents?.length||0} listed</p></div><div className="rounded-xl bg-slate-50 p-3 sm:col-span-2"><p className="text-xs text-slate-500">Next action</p><p className="mt-1 text-sm font-semibold">{r.next_action}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{r.timeline.map((x:string)=><span key={x} className={`rounded-lg px-3 py-2 text-xs font-semibold ${x===r.status?'bg-[#0b1f3a] text-white':'bg-slate-100 text-slate-600'}`}>{x}</span>)}</div>{r.status!=='Completed'&&<button onClick={()=>advance(r)} className="mt-4 rounded-xl border px-4 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50">Advance demo status →</button>}</div>)}</div></div></div>
}
