import Link from 'next/link';import {ArrowRight,CheckCircle2,FileText,Search,ShieldCheck,Landmark,WalletCards,ClipboardList,AlertCircle,BarChart3,UserRound,History,Bookmark,Info,CircleHelp,Presentation} from 'lucide-react';
const meta:any={
'/schemes':['Government Scheme Explorer','Discover government schemes using natural-language search and filters.',Search,['Search schemes','Category filter','State filter','Beneficiary filter','Scheme cards']],
'/eligibility':['Eligibility Checker','Work through a guided profile to identify potentially relevant schemes.',ShieldCheck,['Basic details','Location','Occupation','Income range','Purpose','Scheme-specific questions']],
'/documents':['Document & OCR Assistant','Upload supported documents and prepare them for validation and OCR.',FileText,['PDF / JPG / JPEG / PNG','File validation','Text extraction','Language detection','Document classification']],
'/applications':['Application Guidance Tracker','Follow your application guidance journey with clear next actions.',ClipboardList,['Not Started','Preparing','Submitted','Under Verification','Completed']],
'/grievances':['Grievance Assistant','Turn a service problem into a structured complaint summary and next-step guidance.',AlertCircle,['Payment issue','Application rejection','Document issue','Service delay','Scheme issue','Cooperative issue']],
'/cooperatives':['Cooperative Services','Find guidance for registration, membership, documentation, finance and complaints.',Landmark,['Registration','Membership','Documentation','Finance & Loans','Complaints','Cooperative schemes']],
'/financial-literacy':['Financial Literacy','Simple multilingual explanations of everyday financial topics.',WalletCards,['Savings','Loans','Interest','Credit','Insurance','Digital payments','Fraud awareness']],
'/dashboard':['Citizen Dashboard','A single view of profile completion, conversations, saved schemes and activity.',BarChart3,['Profile completion','Recent conversations','Saved schemes','Potential matches','Applications','Documents']],
'/profile':['Citizen Profile','Maintain the information used by the local scheme-matching engine.',UserRound,['Name','Age','State','District','Occupation','Income range','Farmer status','Land ownership','Preferred language']],
'/history':['Conversation History','Review prior assistance conversations by date, language and category.',History,['Open conversation','Search','Filter','Delete']],
'/saved':['Saved Schemes','Keep useful schemes in one place for later review.',Bookmark,['Save scheme','Remove','Open','Check eligibility']],
'/admin':['Demo Admin Dashboard','Prototype analytics for languages, questions, searches and assistance categories.',BarChart3,['Language distribution','Assistance categories','Scheme searches','Daily activity']],
'/about':['About Sahakar Sahayak','A multilingual citizen-assistance concept designed for transparent, accessible public-service guidance.',Info,['Citizen-first design','Multilingual access','Local deterministic AI fallback','Official-source verification']],
'/help':['Help & FAQ','Learn how the prototype handles assistance, language, documents and demo workflows.',CircleHelp,['How does AI guidance work?','Which languages are supported?','Is eligibility guaranteed?','What does DEMO MODE mean?']],
'/sih-demo':['SIH Presentation','A presentation-ready view of the problem, solution, architecture, innovation and impact.',Presentation,['Problem','Current challenges','Proposed solution','Architecture','Innovation','Impact','Future scope']]
};
export default function FeaturePage({path}:{path:string}){const [title,desc,Icon,items]=meta[path]||meta['/about'];return <div className="min-h-[calc(100vh-4rem)] bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-8 sm:py-10"><div className="rounded-3xl bg-gradient-to-br from-[#0b1f3a] to-[#155eef] p-7 text-white sm:p-10"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/15"><Icon size={24}/></div><div><p className="text-xs font-bold uppercase tracking-wider text-blue-200">SAHAKAR SAHAYAK</p><h1 className="mt-1 text-3xl font-black">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-blue-100">{desc}</p></div></div></div><div className="mt-6 grid gap-5 lg:grid-cols-[1fr_320px]"><section className="card rounded-2xl p-6"><h2 className="text-lg font-bold text-[#0b1f3a]">Prototype workflow</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{items.map((x:string,i:number)=><div key={x} className="flex items-center gap-3 rounded-xl border bg-white p-4"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-50 text-xs font-bold text-blue-700">{i+1}</span><span className="text-sm font-medium text-slate-700">{x}</span><CheckCircle2 className="ml-auto text-green-600" size={16}/></div>)}</div><div className="mt-7 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5"><p className="text-sm font-semibold text-slate-700">Stage 1 UI foundation</p><p className="mt-1 text-sm leading-6 text-slate-500">This page is routed and responsive. Functional data workflows are added in subsequent stages instead of being represented as fake results.</p></div></section><aside className="space-y-4"><div className="card rounded-2xl p-5"><p className="text-sm font-bold">Quick actions</p><div className="mt-3 space-y-2"><Link href="/assistant" className="flex items-center justify-between rounded-xl bg-[#0b1f3a] px-4 py-3 text-sm font-semibold text-white">Ask Sahakar AI <ArrowRight size={16}/></Link><Link href="/schemes" className="flex items-center justify-between rounded-xl border px-4 py-3 text-sm font-semibold text-slate-700">Explore schemes <ArrowRight size={16}/></Link></div></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><b>DEMO MODE</b><br/>Some workflows will use local simulation until real integrations are available.</div></aside></div></div></div>}
