from .database import Base, engine, SessionLocal
from .models import Scheme, User, Profile

SCHEMES = [
{"name":"PM-KISAN","category":"Agriculture","description":"Income support programme for eligible landholding farmer families, subject to the scheme's current rules and exclusions.","benefits":["Income support through scheduled instalments under the scheme"],"eligibility":["Eligible landholding farmer families as defined by current PM-KISAN rules","Subject to exclusions and verification"],"documents":["Aadhaar or prescribed identity details","Landholding/land record details","Bank account details as required"],"application_procedure":["Use the official PM-KISAN portal or designated government channel","Complete registration/details as applicable","Verify status through the official service"],"state_scope":"India","official_url":"https://pmkisan.gov.in/","verification_notes":"Verify current eligibility, exclusions and process on the official PM-KISAN portal."},
{"name":"Pradhan Mantri Fasal Bima Yojana","category":"Agriculture","description":"Crop insurance framework intended to provide insurance coverage for notified crops and risks under applicable state and season notifications.","benefits":["Crop insurance coverage subject to notified terms","Support for covered crop losses under applicable rules"],"eligibility":["Farmers meeting current notified crop, area and season conditions","Eligibility depends on applicable state/season notification"],"documents":["Land/cultivation records as applicable","Bank details","Identity and crop details"],"application_procedure":["Check the current state/season notification","Apply through the designated channel within the applicable timeline","Keep acknowledgement and policy details"],"state_scope":"India; implementation varies by state/season","official_url":"https://pmfby.gov.in/","verification_notes":"Coverage, notified crops, risks and deadlines must be verified for the relevant state and season."},
{"name":"Kisan Credit Card","category":"Finance","description":"Credit facility framework for eligible farmers for agricultural and allied activities through participating financial institutions.","benefits":["Access to agricultural credit subject to lender assessment and scheme rules","Working capital support for eligible agricultural needs"],"eligibility":["Eligible farmers and other permitted categories under current banking guidelines","Subject to lender documentation and assessment"],"documents":["Identity/address documents","Land or cultivation documents as applicable","Bank-required documents"],"application_procedure":["Approach a participating bank or eligible financial institution","Submit required documents","Complete lender verification and sanction process"],"state_scope":"India","official_url":"https://www.nabard.org/","verification_notes":"Loan amount, interest, collateral and eligibility depend on current rules and lender assessment."},
{"name":"Pradhan Mantri Mudra Yojana","category":"Business","description":"Micro-enterprise credit framework offered through eligible lending institutions for qualifying non-corporate, non-farm small/micro enterprises.","benefits":["Business credit through eligible lending institutions","Financing categories depend on current scheme and lender rules"],"eligibility":["Eligible micro/small non-corporate, non-farm enterprises","Subject to lender assessment and current scheme rules"],"documents":["Identity and address proof","Business details","Bank/lender-required financial documents"],"application_procedure":["Identify an eligible lending institution","Submit the business and KYC information requested","Complete lender assessment"],"state_scope":"India","official_url":"https://www.mudra.org.in/","verification_notes":"Loan approval is not guaranteed; verify current product terms with the official/lending institution."},
{"name":"Pradhan Mantri Awas Yojana","category":"Housing","description":"Government housing assistance framework with separate urban and rural components and eligibility criteria that depend on the applicable component.","benefits":["Housing assistance under the applicable PMAY component and current rules"],"eligibility":["Eligibility depends on whether PMAY-Urban or PMAY-Gramin applies","Household and other current criteria must be verified"],"documents":["Identity/address documents","Household and income information as applicable","Property/housing records as required"],"application_procedure":["Identify the applicable PMAY component","Use the designated official government channel","Submit information and complete verification"],"state_scope":"India","official_url":"https://pmaymis.gov.in/","verification_notes":"Verify the applicable PMAY component and current eligibility on the official government portal."},
{"name":"Pradhan Mantri Jan-Dhan Yojana","category":"Finance","description":"Financial inclusion programme supporting access to basic banking services through participating banks.","benefits":["Access to basic banking services under applicable account features","Financial inclusion support subject to current bank rules"],"eligibility":["Eligible individuals seeking access to basic banking services","KYC and bank requirements apply"],"documents":["KYC/identity documents as required by the bank","Address information as applicable"],"application_procedure":["Visit a participating bank branch or permitted channel","Complete KYC/account-opening requirements","Confirm available features with the bank"],"state_scope":"India","official_url":"https://pmjdy.gov.in/","verification_notes":"Account features and eligibility should be confirmed with the participating bank and official programme information."},
]

def seed():
    Base.metadata.create_all(bind=engine)
    db=SessionLocal()
    try:
        if db.query(Scheme).count()==0:
            db.add_all([Scheme(**x) for x in SCHEMES])
        if db.query(User).count()==0:
            user=User(name="Demo Citizen"); db.add(user); db.flush(); db.add(Profile(user_id=user.id))
        db.commit()
    finally: db.close()

if __name__ == "__main__": seed()
