'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowRight,Bookmark,FileText,MessageSquare,UserRound,ClipboardList} from 'lucide-react';
import {api} from '@/lib/api';
export default function Page(){
 const [d,setD]=useState<any>(null); const [error,setError]=useState('');
 useEffect(()=>{api.dashboard().then(setD).catch(e=>setError(e.message||'Unable to load dashboard'))},[]);
 if(error)return <div className="p-8"><div className="rounded-2xl bg-red-50 p-5 text-red-700">{error}</div></div>;
 if(!d)return <div className="p-8 text-slate-500">Loading citizen dashboard…</div>;
 const cards=[['Profile completion',`${d.profile_completion}%`,UserRound,'/profile'],['Saved schemes',d.saved_schemes_count,Bookmark,'/saved'],['Applications',d.applications_count,ClipboardList,'/applications'],['Documents',d.documents_count,FileText,'/documents']];
 return <div className="min-h-[calc(100vh-4rem)] bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-8"><div className="rounded-3xl bg-gradient-to-br from-[#0b1f3a] to-[#155eef] p-7 text-white sm:p-10"><p className="text-xs font-bold uppercase tracking-wider text-blue-200">CITIZEN DASHBOARD</p><h1 className="mt-2 text-3xl font-black">Welcome, {d.citizen_name}</h1><p className="mt-2 text-sm text-blue-100">Your saved schemes, conversations, documents and application guidance in one place.</p></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value,Icon,href]:any)=><Link href={href} key={label} className="card rounded-2xl p-5 hover:-translate-y-0.5"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">{label}</span><Icon size={18} className="text-blue-600"/></div><p className="mt-3 text-3xl font-black text-[#0b1f3a]">{value}</p></Link>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="card rounded-2xl p-6"><div className="flex items-center justify-between"><h2 className="font-bold text-[#0b1f3a]">Recent conversations</h2><Link href="/history" className="text-sm font-semibold text-blue-700">View history →</Link></div>{d.recent_conversations.length?<div className="mt-4 space-y-3">{d.recent_conversations.map((c:any)=><Link href={`/history?conversation=${c.id}`} key={c.id} className="flex items-center gap-3 rounded-xl border p-4 hover:bg-slate-50"><MessageSquare size={18} className="text-blue-600"/><span className="text-sm font-medium text-slate-700">{c.title}</span><ArrowRight size={16} className="ml-auto text-slate-400"/></Link>)}</div>:<p className="mt-4 text-sm text-slate-500">No conversations yet. Ask Sahakar AI to start.</p>}</section><section className="card rounded-2xl p-6"><h2 className="font-bold text-[#0b1f3a]">Quick actions</h2><div className="mt-4 space-y-2">{[['Ask AI','/assistant'],['Find schemes','/schemes'],['Check eligibility','/eligibility'],['Upload document','/documents']].map(([x,h])=><Link href={h} key={h} className="flex items-center justify-between rounded-xl border px-4 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50">{x}<ArrowRight size={16}/></Link>)}</div><div className="mt-5 rounded-xl bg-amber-50 p-4 text-xs leading-5 text-amber-900"><b>DEMO MODE</b><br/>Application status and analytics are simulated. Government eligibility and submission must be verified through official channels.</div></section></div></div></div>
}
