'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowLeft, ArrowRight, CheckCircle2, CircleHelp, ShieldCheck, ExternalLink, AlertTriangle} from 'lucide-react';
import {api} from '@/lib/api';

const steps=[
  ['Basic details','age'],['Location','state'],['Occupation','occupation'],['Income range','income_range'],['Purpose','purpose'],['Additional details','land_ownership']
];
const options:any={
  occupation:['Farmer','Business / self-employed','Student','Employee','Other'],
  income_range:['Below ₹1 lakh','₹1–3 lakh','₹3–5 lakh','₹5–10 lakh','Above ₹10 lakh','Prefer not to say'],
  purpose:['Seeds / farming inputs','Crop loss / damage','Agricultural loan','Start a business','Housing assistance','Basic banking / finance','Other'],
  land_ownership:['Own land','Lease / cultivate land','No land ownership','Not sure'],
};
const fieldLabel:any={age:'Age',state:'State',occupation:'Occupation',income_range:'Annual income range',purpose:'What assistance do you need?',land_ownership:'Land ownership'};

export default function EligibilityPage(){
 const [step,setStep]=useState(0); const [answers,setAnswers]=useState<any>({}); const [loading,setLoading]=useState(false); const [result,setResult]=useState<any>(null); const [error,setError]=useState('');
 const key=steps[step][1]; const set=(v:any)=>setAnswers((a:any)=>({...a,[key]:v}));
 const submit=async()=>{setLoading(true);setError('');try{const r=await api.eligibility({session_id:result?.session_id,answers});setResult(r); if(!r.complete){const first=r.missing_fields[0]; const i=steps.findIndex(s=>s[1]===first); if(i>=0)setStep(i)}}catch(e:any){setError(e.message||'Could not complete eligibility guidance.')}finally{setLoading(false)}};
 return <div className="min-h-[calc(100vh-4rem)] bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-8 sm:py-10">
  <div className="rounded-3xl bg-gradient-to-br from-[#0b1f3a] to-[#155eef] p-7 text-white sm:p-10"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/15"><ShieldCheck/></div><div><p className="text-xs font-bold uppercase tracking-wider text-blue-200">SAHAKAR SAHAYAK</p><h1 className="mt-1 text-3xl font-black">Eligibility Guidance</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-blue-100">Answer a few questions to identify potentially relevant schemes. This is guidance, not a guaranteed eligibility decision.</p></div></div></div>
  <div className="mt-6 grid gap-5 lg:grid-cols-[280px_1fr]">
   <aside className="card rounded-2xl p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Guided check</p>{steps.map((s,i)=><div key={s[1]} className={`mt-2 flex items-center gap-3 rounded-xl px-3 py-3 text-sm ${i===step?'bg-blue-50 text-blue-700':'text-slate-500'}`}><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${i<step?'bg-green-100 text-green-700':i===step?'bg-blue-600 text-white':'bg-slate-100'}`}>{i<step?<CheckCircle2 size={15}/>:i+1}</span>{s[0]}</div>)}<div className="mt-5 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-900"><b>DEMO / GUIDANCE</b><br/>The engine compares the information you provide with local scheme metadata. Verify current rules on official portals.</div></aside>
   <section className="card rounded-2xl p-5 sm:p-7">
    {!result?.complete ? <><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Step {step+1} of {steps.length}</p><h2 className="mt-1 text-2xl font-black text-[#0b1f3a]">{steps[step][0]}</h2></div><CircleHelp className="text-slate-300"/></div>
     <div className="mt-7">{key==='age'?<input type="number" min="1" max="120" value={answers[key]||''} onChange={e=>set(e.target.value?Number(e.target.value):'')} placeholder="Enter age" className="w-full rounded-xl border px-4 py-3 outline-none focus:border-blue-500"/>:key==='state'?<input value={answers[key]||''} onChange={e=>set(e.target.value)} placeholder="e.g. Maharashtra" className="w-full rounded-xl border px-4 py-3 outline-none focus:border-blue-500"/>:<div className="grid gap-3 sm:grid-cols-2">{(options[key]||[]).map((o:string)=><button key={o} onClick={()=>set(o)} className={`rounded-xl border p-4 text-left text-sm font-semibold transition ${answers[key]===o?'border-blue-500 bg-blue-50 text-blue-700':'bg-white hover:border-blue-300'}`}>{o}</button>)}</div>}</div>
     <div className="mt-8 flex justify-between"><button disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))} className="flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-semibold disabled:opacity-40"><ArrowLeft size={16}/> Back</button>{step<steps.length-1?<button disabled={!answers[key]} onClick={()=>setStep(step+1)} className="flex items-center gap-2 rounded-xl bg-[#0b1f3a] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Next <ArrowRight size={16}/></button>:<button disabled={!answers[key]||loading} onClick={submit} className="rounded-xl bg-[#155eef] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{loading?'Analyzing…':'Find potentially relevant schemes'}</button>}</div>
    </>:<Results result={result} answers={answers} onReset={()=>{setResult(null);setStep(0)}}/>}
    {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
   </section>
  </div>
 </div></div>
}
function Results({result,answers,onReset}:{result:any,answers:any,onReset:()=>void}){return <div><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-green-600">Guidance result</p><h2 className="mt-1 text-2xl font-black text-[#0b1f3a]">Potentially relevant schemes</h2><p className="mt-2 text-sm text-slate-500">Based on the information you provided: {Object.values(answers).filter(Boolean).join(' • ')}</p></div><button onClick={onReset} className="rounded-xl border px-4 py-2 text-sm font-semibold">Start over</button></div><div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><AlertTriangle className="mr-2 inline" size={16}/>{result.disclaimer}</div><div className="mt-5 space-y-4">{result.results.map((r:any)=><div key={r.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{r.category}</span><h3 className="mt-3 text-lg font-bold text-[#0b1f3a]">{r.name}</h3></div><Link href={`/schemes/${r.id}`} className="flex items-center gap-1 text-sm font-semibold text-blue-700">Details <ArrowRight size={15}/></Link></div><div className="mt-4 grid gap-4 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Why it may match</p><ul className="mt-2 space-y-1 text-sm text-slate-700">{(r.why_match||[]).map((x:string)=><li key={x}>✓ {x}</li>)}</ul></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Missing information</p>{r.missing_information?.length?<ul className="mt-2 space-y-1 text-sm text-slate-700">{r.missing_information.map((x:string)=><li key={x}>! {x.replaceAll('_',' ')}</li>)}</ul>:<p className="mt-2 text-sm text-slate-600">No additional fields required by this local guidance rule.</p>}</div></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><b className="text-xs uppercase text-slate-400">Benefits</b><p className="mt-1 text-sm">{r.benefits?.[0]}</p></div><div className="rounded-xl bg-slate-50 p-3"><b className="text-xs uppercase text-slate-400">Documents</b><p className="mt-1 text-sm">{(r.documents||[]).slice(0,2).join(', ')}</p></div><div className="rounded-xl bg-slate-50 p-3"><b className="text-xs uppercase text-slate-400">Application</b><p className="mt-1 text-sm">{r.application_procedure?.[0]}</p></div></div><a href={r.official_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-blue-700">Verify official source <ExternalLink size={14}/></a></div>)}</div></div>}
